-- PostgreSQL schema for mbkauthe (standard lowercase snake_case).

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Table: mbkcore_users
CREATE TABLE IF NOT EXISTS mbkcore_users (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    username character varying(50),
    password text DEFAULT '12345670'::text,
    is_active boolean DEFAULT false,
    role text DEFAULT 'normaluser'::text,
    have_mail_account boolean DEFAULT false,
    allowed_apps jsonb DEFAULT '["Portal", "mbkauthe"]'::jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_login timestamp with time zone,
    password_hash character varying(255),
    full_name character varying(100),
    user_id character varying(9),
    email text DEFAULT 'support@mbktech.org'::text,
    image text DEFAULT 'https://portal.mbktech.org/icon.svg'::text,
    bio text DEFAULT 'I am ....'::text,
    social_accounts text DEFAULT '{}'::text,
    positions jsonb DEFAULT '{"Not_Permanent": "Member Is Not Permanent"}'::jsonb,
    permission_templates jsonb DEFAULT '[]'::jsonb,
    perm_version integer DEFAULT 1,
    CONSTRAINT mbkcore_users_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_users_username_key UNIQUE (username),
    CONSTRAINT mbkcore_users_user_id_key UNIQUE (user_id),
    CONSTRAINT chk_mbkcore_users_user_id_length CHECK (user_id IS NULL OR length(user_id) = 9)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_is_active ON mbkcore_users USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_allowed_apps_gin ON mbkcore_users USING gin (allowed_apps);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_email ON mbkcore_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_last_login ON mbkcore_users USING btree (last_login);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_positions_gin ON mbkcore_users USING gin (positions);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_role ON mbkcore_users USING btree (role);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_username_cover ON mbkcore_users USING btree (username) INCLUDE (is_active, role);
CREATE INDEX IF NOT EXISTS idx_mbkcore_users_user_id ON mbkcore_users USING btree (user_id);
COMMENT ON TABLE mbkcore_users IS '[core]';

-- Table: mbkcore_api_tokens
CREATE TABLE IF NOT EXISTS mbkcore_api_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    token_hash character varying(128) NOT NULL,
    prefix character varying(32) NOT NULL,
    permissions jsonb DEFAULT '{"permissions": []}'::jsonb NOT NULL,
    last_used timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT mbkcore_api_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_api_tokens_token_hash_key UNIQUE (token_hash),
    CONSTRAINT chk_mbkcore_api_tokens_name_not_empty CHECK ((length(TRIM(BOTH FROM name)) > 0)),
    CONSTRAINT chk_mbkcore_api_tokens_expires_future CHECK (((expires_at IS NULL) OR (expires_at > created_at)))
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_api_tokens_expires ON mbkcore_api_tokens USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mbkcore_api_tokens_permissions_gin ON mbkcore_api_tokens USING gin (permissions);
CREATE INDEX IF NOT EXISTS idx_mbkcore_api_tokens_username_created ON mbkcore_api_tokens USING btree (username, created_at DESC);
COMMENT ON TABLE mbkcore_api_tokens IS '[core]';

-- Table: mbkcore_api_token_profiles
CREATE TABLE IF NOT EXISTS mbkcore_api_token_profiles (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    permissions jsonb,
    profile_key character varying(32),
    expires_in_days integer,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT mbkcore_api_token_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_api_token_profiles_name_key UNIQUE (name),
    CONSTRAINT mbkcore_api_token_profiles_profile_key_key UNIQUE (profile_key),
    CONSTRAINT chk_mbkcore_api_token_profiles_expires CHECK (((expires_in_days IS NULL) OR (expires_in_days > 0)))
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_api_token_profiles_is_active ON mbkcore_api_token_profiles USING btree (is_active);
COMMENT ON TABLE mbkcore_api_token_profiles IS '[core]';

-- Table: mbkcore_cli_auth_sessions
CREATE TABLE IF NOT EXISTS mbkcore_cli_auth_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device_code_hash character varying(64) NOT NULL,
    user_code_hash character varying(64) NOT NULL,
    client_name character varying(255) NOT NULL,
    profile_id integer NOT NULL,
    username character varying(50),
    token_id integer,
    pending_token text,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    approved_at timestamp with time zone,
    CONSTRAINT mbkcore_cli_auth_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_cli_auth_sessions_device_code_hash_key UNIQUE (device_code_hash),
    CONSTRAINT mbkcore_cli_auth_sessions_user_code_hash_key UNIQUE (user_code_hash),
    CONSTRAINT chk_mbkcore_cli_auth_sessions_status CHECK (((status::text) = ANY (ARRAY['pending'::text, 'approved'::text, 'completed'::text, 'denied'::text, 'expired'::text])))
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_cli_auth_sessions_expires ON mbkcore_cli_auth_sessions USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mbkcore_cli_auth_sessions_status ON mbkcore_cli_auth_sessions USING btree (status);
COMMENT ON TABLE mbkcore_cli_auth_sessions IS '[core]';

-- Table: mbkcore_password_resets
CREATE TABLE IF NOT EXISTS mbkcore_password_resets (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    reset_token text,
    reset_token_expires timestamp with time zone,
    reset_attempts integer DEFAULT 0,
    last_reset_attempt timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mbkcore_password_resets_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_password_resets_token ON mbkcore_password_resets USING btree (reset_token);
COMMENT ON TABLE mbkcore_password_resets IS '[core]';

-- Table: mbkcore_sessions
CREATE TABLE IF NOT EXISTS mbkcore_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    meta jsonb,
    CONSTRAINT mbkcore_sessions_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_sessions_expires ON mbkcore_sessions USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mbkcore_sessions_user_created ON mbkcore_sessions USING btree (username, created_at);
CREATE INDEX IF NOT EXISTS idx_mbkcore_sessions_username_expires ON mbkcore_sessions USING btree (username, expires_at);
COMMENT ON TABLE mbkcore_sessions IS '[core]';

-- Table: mbkcore_trusted_devices
CREATE TABLE IF NOT EXISTS mbkcore_trusted_devices (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    device_token character varying(64) NOT NULL,
    device_name character varying(255),
    user_agent text,
    ip_address character varying(45),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp with time zone NOT NULL,
    last_used timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mbkcore_trusted_devices_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_trusted_devices_device_token_key UNIQUE (device_token)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_trusted_devices_expires ON mbkcore_trusted_devices USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_mbkcore_trusted_devices_username_expires ON mbkcore_trusted_devices USING btree (username, expires_at);
CREATE INDEX IF NOT EXISTS idx_mbkcore_trusted_devices_token_user_expires ON mbkcore_trusted_devices USING btree (device_token, username, expires_at);
COMMENT ON TABLE mbkcore_trusted_devices IS '[core]';

-- Table: mbkcore_two_factor
CREATE TABLE IF NOT EXISTS mbkcore_two_factor (
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    is_enabled boolean DEFAULT false NOT NULL,
    two_fa_secret text,
    CONSTRAINT mbkcore_two_factor_pkey PRIMARY KEY (username)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_two_factor_username_status ON mbkcore_two_factor USING btree (username, is_enabled);
COMMENT ON TABLE mbkcore_two_factor IS '[core]';

-- Table: mbkcore_session (express-session store)
CREATE TABLE IF NOT EXISTS mbkcore_session (
    sid character varying NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL,
    username character varying(50) REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    last_activity timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mbkcore_session_pkey PRIMARY KEY (sid)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_session_expire ON mbkcore_session USING btree (expire);
CREATE INDEX IF NOT EXISTS idx_mbkcore_session_last_activity ON mbkcore_session USING btree (last_activity);
CREATE INDEX IF NOT EXISTS idx_mbkcore_session_user_id ON mbkcore_session USING btree ((((sess -> 'user'::text) ->> 'id'::text)));
COMMENT ON TABLE mbkcore_session IS '[core]';

-- Table: mbkcore_user_github
CREATE TABLE IF NOT EXISTS mbkcore_user_github (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    github_id character varying(255),
    github_username character varying(255),
    access_token text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    installation_id bigint,
    installation_target_type character varying(32),
    CONSTRAINT mbkcore_user_github_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_user_github_github_id_key UNIQUE (github_id)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_user_github_username ON mbkcore_user_github USING btree (username);
COMMENT ON TABLE mbkcore_user_github IS '[core]';

-- Table: mbkcore_user_google
CREATE TABLE IF NOT EXISTS mbkcore_user_google (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) REFERENCES mbkcore_users(username),
    google_id character varying(255),
    google_email character varying(255),
    access_token text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT mbkcore_user_google_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_user_google_google_id_key UNIQUE (google_id)
);
COMMENT ON TABLE mbkcore_user_google IS '[core]';

-- Table: mbkcore_permission_catalog
CREATE TABLE IF NOT EXISTS mbkcore_permission_catalog (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_key varchar(50) NOT NULL,
    service_key varchar(50) NOT NULL,
    action_key varchar(50) NOT NULL,
    label text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT mbkcore_permission_catalog_pkey PRIMARY KEY (id),
    CONSTRAINT uq_permission_catalog UNIQUE (app_key, service_key, action_key)
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_permission_catalog_app ON mbkcore_permission_catalog USING btree (app_key);
CREATE INDEX IF NOT EXISTS idx_mbkcore_permission_catalog_app_active ON mbkcore_permission_catalog USING btree (app_key, is_active);
CREATE INDEX IF NOT EXISTS idx_mbkcore_permission_catalog_app_service ON mbkcore_permission_catalog USING btree (app_key, service_key);
COMMENT ON TABLE mbkcore_permission_catalog IS '[core]';

-- Built-in permission shared by every application; app sync never manages it.
INSERT INTO mbkcore_permission_catalog (app_key, service_key, action_key, label, is_active)
VALUES ('global', 'basic', 'access', 'Basic global access', true)
ON CONFLICT (app_key, service_key, action_key)
DO UPDATE SET label = EXCLUDED.label, is_active = true, updated_at = now();

-- Table: mbkcore_permission_templates
CREATE TABLE IF NOT EXISTS mbkcore_permission_templates (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(50) NOT NULL,
    permissions jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT mbkcore_permission_templates_pkey PRIMARY KEY (id),
    CONSTRAINT mbkcore_permission_templates_name_key UNIQUE (name)
);
COMMENT ON TABLE mbkcore_permission_templates IS '[core]';

-- Table: mbkcore_user_permission_overrides
CREATE TABLE IF NOT EXISTS mbkcore_user_permission_overrides (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(50) NOT NULL REFERENCES mbkcore_users(username) ON DELETE CASCADE,
    permission character varying(150) NOT NULL,
    effect character varying(5) NOT NULL,
    granted_by character varying(50),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT mbkcore_user_permission_overrides_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_perm_override UNIQUE (username, permission),
    CONSTRAINT chk_user_perm_override_effect CHECK (effect IN ('allow', 'deny'))
);
CREATE INDEX IF NOT EXISTS idx_mbkcore_user_permission_overrides_username ON mbkcore_user_permission_overrides USING btree (username);
COMMENT ON TABLE mbkcore_user_permission_overrides IS '[core]';

-- Seed user (hash-only)
INSERT INTO mbkcore_users (username, password_hash, role, is_active, have_mail_account, full_name)
VALUES ('support', 'b8b10c1c9006d8c30ab81c412463c65ff6dae3293d9bfbaf5fd8e275081d0947f000a828004e2fbd3a8f6ef5a35ae3eddd4c57b00ecab376b12e607a16a57459', 'superadmin', true, false, 'Support User')
ON CONFLICT (username) DO NOTHING;
